[theme]
base                     = "light"
primaryColor             = "#2e41d4"
backgroundColor          = "#f0f2f8"
secondaryBackgroundColor = "#ffffff"
textColor                = "#1a1d3a"
font                     = "sans serif"

[server]
headless = true
